theme: jekyll-theme-minimal
title: Uyen Dang's Blog
author: Uyen Dang
email: dtleuyen@gmail.com
description: Research Interests: Missing Data, Medical Imaging, XAI, AI Bias.

social-links:
- LinkedIn: https://linkedin.com/in/leuyendt
- GitHub: https://github.com/DangLeUyen
